### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by ruiwenfan** [WangXFng/STaTRL#1]
Thank you very much for the code provided, I really appreciate your excellent work and I am reproducing your work. But I found that only one dataset is provided in GitHub, could you please provide the other datasets mentioned in the paper？

**Comment by WangXFng** [comment]
I didn't understand your question very well. Anyway, I have to clarify that there is only one dataset with available textual reviews (i.e., Yelp2020), which means others are only based on user-POI interactions.

Here is a simplified repository for STaTRL: https://github.com/WangXFng/STRL. In it, you can use five datasets and it is much easier to run, as it is without text representation.

Thank you for your attention. I hope my reply could help you.

**Comment by ruiwenfan** [comment]
I didn't see https://github.com/WangXFng/STRL. thanks for your answer.
